/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business.index'
import { Route as AuthenticatedBusinessSlugRouteImport } from './routes/_authenticated/business.$slug'
import { Route as AuthenticatedBusinessNewRouteImport } from './routes/_authenticated/business.new'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedInboxIdRouteImport } from './routes/_authenticated/inbox.$id'
import { Route as AuthenticatedBusinessSlugIndexRouteImport } from './routes/_authenticated/business.$slug.index'
import { Route as AuthenticatedBusinessSlugAnalyticsRouteImport } from './routes/_authenticated/business.$slug.analytics'
import { Route as AuthenticatedBusinessSlugInventoryRouteImport } from './routes/_authenticated/business.$slug.inventory'
import { Route as AuthenticatedBusinessSlugReceptionistRouteImport } from './routes/_authenticated/business.$slug.receptionist'
import { Route as AuthenticatedBusinessSlugSettingsRouteImport } from './routes/_authenticated/business.$slug.settings'
import { Route as AuthenticatedBusinessSlugMessagesIndexRouteImport } from './routes/_authenticated/business.$slug.messages.index'
import { Route as AuthenticatedBusinessSlugMessagesIdRouteImport } from './routes/_authenticated/business.$slug.messages.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/business/',
    path: '/business/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSlugRoute =
  AuthenticatedBusinessSlugRouteImport.update({
    id: '/business/$slug',
    path: '/business/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessNewRoute =
  AuthenticatedBusinessNewRouteImport.update({
    id: '/business/new',
    path: '/business/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxIdRoute = AuthenticatedInboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessSlugIndexRoute =
  AuthenticatedBusinessSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)
const AuthenticatedBusinessSlugAnalyticsRoute =
  AuthenticatedBusinessSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)
const AuthenticatedBusinessSlugInventoryRoute =
  AuthenticatedBusinessSlugInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)
const AuthenticatedBusinessSlugReceptionistRoute =
  AuthenticatedBusinessSlugReceptionistRouteImport.update({
    id: '/receptionist',
    path: '/receptionist',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)
const AuthenticatedBusinessSlugSettingsRoute =
  AuthenticatedBusinessSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)
const AuthenticatedBusinessSlugMessagesIndexRoute =
  AuthenticatedBusinessSlugMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)
const AuthenticatedBusinessSlugMessagesIdRoute =
  AuthenticatedBusinessSlugMessagesIdRouteImport.update({
    id: '/messages/$id',
    path: '/messages/$id',
    getParentRoute: () => AuthenticatedBusinessSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/api/chat': typeof ApiChatRoute
  '/b/$slug': typeof BSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/business/$slug': typeof AuthenticatedBusinessSlugRouteWithChildren
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
  '/business/$slug/analytics': typeof AuthenticatedBusinessSlugAnalyticsRoute
  '/business/$slug/inventory': typeof AuthenticatedBusinessSlugInventoryRoute
  '/business/$slug/receptionist': typeof AuthenticatedBusinessSlugReceptionistRoute
  '/business/$slug/settings': typeof AuthenticatedBusinessSlugSettingsRoute
  '/business/$slug/': typeof AuthenticatedBusinessSlugIndexRoute
  '/business/$slug/messages/$id': typeof AuthenticatedBusinessSlugMessagesIdRoute
  '/business/$slug/messages/': typeof AuthenticatedBusinessSlugMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/api/chat': typeof ApiChatRoute
  '/b/$slug': typeof BSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
  '/business/$slug/analytics': typeof AuthenticatedBusinessSlugAnalyticsRoute
  '/business/$slug/inventory': typeof AuthenticatedBusinessSlugInventoryRoute
  '/business/$slug/receptionist': typeof AuthenticatedBusinessSlugReceptionistRoute
  '/business/$slug/settings': typeof AuthenticatedBusinessSlugSettingsRoute
  '/business/$slug': typeof AuthenticatedBusinessSlugIndexRoute
  '/business/$slug/messages/$id': typeof AuthenticatedBusinessSlugMessagesIdRoute
  '/business/$slug/messages': typeof AuthenticatedBusinessSlugMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/api/chat': typeof ApiChatRoute
  '/b/$slug': typeof BSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_authenticated/business/$slug': typeof AuthenticatedBusinessSlugRouteWithChildren
  '/_authenticated/business/new': typeof AuthenticatedBusinessNewRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
  '/_authenticated/business/$slug/analytics': typeof AuthenticatedBusinessSlugAnalyticsRoute
  '/_authenticated/business/$slug/inventory': typeof AuthenticatedBusinessSlugInventoryRoute
  '/_authenticated/business/$slug/receptionist': typeof AuthenticatedBusinessSlugReceptionistRoute
  '/_authenticated/business/$slug/settings': typeof AuthenticatedBusinessSlugSettingsRoute
  '/_authenticated/business/$slug/': typeof AuthenticatedBusinessSlugIndexRoute
  '/_authenticated/business/$slug/messages/$id': typeof AuthenticatedBusinessSlugMessagesIdRoute
  '/_authenticated/business/$slug/messages/': typeof AuthenticatedBusinessSlugMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/feed'
    | '/search'
    | '/appointments'
    | '/conversations'
    | '/dashboard'
    | '/me'
    | '/messages'
    | '/my-bookings'
    | '/services'
    | '/setup'
    | '/api/chat'
    | '/b/$slug'
    | '/store/$slug'
    | '/business/$slug'
    | '/business/new'
    | '/chat/$id'
    | '/inbox/$id'
    | '/business/'
    | '/business/$slug/analytics'
    | '/business/$slug/inventory'
    | '/business/$slug/receptionist'
    | '/business/$slug/settings'
    | '/business/$slug/'
    | '/business/$slug/messages/$id'
    | '/business/$slug/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/feed'
    | '/search'
    | '/appointments'
    | '/conversations'
    | '/dashboard'
    | '/me'
    | '/messages'
    | '/my-bookings'
    | '/services'
    | '/setup'
    | '/api/chat'
    | '/b/$slug'
    | '/store/$slug'
    | '/business/new'
    | '/chat/$id'
    | '/inbox/$id'
    | '/business'
    | '/business/$slug/analytics'
    | '/business/$slug/inventory'
    | '/business/$slug/receptionist'
    | '/business/$slug/settings'
    | '/business/$slug'
    | '/business/$slug/messages/$id'
    | '/business/$slug/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/feed'
    | '/search'
    | '/_authenticated/appointments'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/my-bookings'
    | '/_authenticated/services'
    | '/_authenticated/setup'
    | '/api/chat'
    | '/b/$slug'
    | '/store/$slug'
    | '/_authenticated/business/$slug'
    | '/_authenticated/business/new'
    | '/_authenticated/chat/$id'
    | '/_authenticated/inbox/$id'
    | '/_authenticated/business/'
    | '/_authenticated/business/$slug/analytics'
    | '/_authenticated/business/$slug/inventory'
    | '/_authenticated/business/$slug/receptionist'
    | '/_authenticated/business/$slug/settings'
    | '/_authenticated/business/$slug/'
    | '/_authenticated/business/$slug/messages/$id'
    | '/_authenticated/business/$slug/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  SearchRoute: typeof SearchRoute
  ApiChatRoute: typeof ApiChatRoute
  BSlugRoute: typeof BSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/$slug': {
      id: '/_authenticated/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof AuthenticatedBusinessSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/new': {
      id: '/_authenticated/business/new'
      path: '/business/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof AuthenticatedBusinessNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$id': {
      id: '/_authenticated/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AuthenticatedInboxIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/$slug/': {
      id: '/_authenticated/business/$slug/'
      path: '/'
      fullPath: '/business/$slug/'
      preLoaderRoute: typeof AuthenticatedBusinessSlugIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
    '/_authenticated/business/$slug/analytics': {
      id: '/_authenticated/business/$slug/analytics'
      path: '/analytics'
      fullPath: '/business/$slug/analytics'
      preLoaderRoute: typeof AuthenticatedBusinessSlugAnalyticsRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
    '/_authenticated/business/$slug/inventory': {
      id: '/_authenticated/business/$slug/inventory'
      path: '/inventory'
      fullPath: '/business/$slug/inventory'
      preLoaderRoute: typeof AuthenticatedBusinessSlugInventoryRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
    '/_authenticated/business/$slug/receptionist': {
      id: '/_authenticated/business/$slug/receptionist'
      path: '/receptionist'
      fullPath: '/business/$slug/receptionist'
      preLoaderRoute: typeof AuthenticatedBusinessSlugReceptionistRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
    '/_authenticated/business/$slug/settings': {
      id: '/_authenticated/business/$slug/settings'
      path: '/settings'
      fullPath: '/business/$slug/settings'
      preLoaderRoute: typeof AuthenticatedBusinessSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
    '/_authenticated/business/$slug/messages/': {
      id: '/_authenticated/business/$slug/messages/'
      path: '/messages'
      fullPath: '/business/$slug/messages/'
      preLoaderRoute: typeof AuthenticatedBusinessSlugMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
    '/_authenticated/business/$slug/messages/$id': {
      id: '/_authenticated/business/$slug/messages/$id'
      path: '/messages/$id'
      fullPath: '/business/$slug/messages/$id'
      preLoaderRoute: typeof AuthenticatedBusinessSlugMessagesIdRouteImport
      parentRoute: typeof AuthenticatedBusinessSlugRoute
    }
  }
}

interface AuthenticatedBusinessSlugRouteChildren {
  AuthenticatedBusinessSlugAnalyticsRoute: typeof AuthenticatedBusinessSlugAnalyticsRoute
  AuthenticatedBusinessSlugInventoryRoute: typeof AuthenticatedBusinessSlugInventoryRoute
  AuthenticatedBusinessSlugReceptionistRoute: typeof AuthenticatedBusinessSlugReceptionistRoute
  AuthenticatedBusinessSlugSettingsRoute: typeof AuthenticatedBusinessSlugSettingsRoute
  AuthenticatedBusinessSlugIndexRoute: typeof AuthenticatedBusinessSlugIndexRoute
  AuthenticatedBusinessSlugMessagesIdRoute: typeof AuthenticatedBusinessSlugMessagesIdRoute
  AuthenticatedBusinessSlugMessagesIndexRoute: typeof AuthenticatedBusinessSlugMessagesIndexRoute
}

const AuthenticatedBusinessSlugRouteChildren: AuthenticatedBusinessSlugRouteChildren =
  {
    AuthenticatedBusinessSlugAnalyticsRoute:
      AuthenticatedBusinessSlugAnalyticsRoute,
    AuthenticatedBusinessSlugInventoryRoute:
      AuthenticatedBusinessSlugInventoryRoute,
    AuthenticatedBusinessSlugReceptionistRoute:
      AuthenticatedBusinessSlugReceptionistRoute,
    AuthenticatedBusinessSlugSettingsRoute:
      AuthenticatedBusinessSlugSettingsRoute,
    AuthenticatedBusinessSlugIndexRoute: AuthenticatedBusinessSlugIndexRoute,
    AuthenticatedBusinessSlugMessagesIdRoute:
      AuthenticatedBusinessSlugMessagesIdRoute,
    AuthenticatedBusinessSlugMessagesIndexRoute:
      AuthenticatedBusinessSlugMessagesIndexRoute,
  }

const AuthenticatedBusinessSlugRouteWithChildren =
  AuthenticatedBusinessSlugRoute._addFileChildren(
    AuthenticatedBusinessSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedBusinessSlugRoute: typeof AuthenticatedBusinessSlugRouteWithChildren
  AuthenticatedBusinessNewRoute: typeof AuthenticatedBusinessNewRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedInboxIdRoute: typeof AuthenticatedInboxIdRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedBusinessSlugRoute: AuthenticatedBusinessSlugRouteWithChildren,
  AuthenticatedBusinessNewRoute: AuthenticatedBusinessNewRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedInboxIdRoute: AuthenticatedInboxIdRoute,
  AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  SearchRoute: SearchRoute,
  ApiChatRoute: ApiChatRoute,
  BSlugRoute: BSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
